version: "3.7"
services:
  checker:
    build:
      context: .
      dockerfile: Dockerfile_checker
    volumes:
      - ./output:/code/output
    environment:
      TZ: Europe/Prague
  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    volumes:
      - ./output:/code/output
    environment:
      TELEGRAM_BOT_TOKEN: "$TELEGRAM_BOT_TOKEN"
      DEVELOPER_CHAT_ID: "$DEVELOPER_CHAT_ID"
      POLLING_INTERVAL: 17
      TZ: Europe/Prague
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
       - ./storage/redis/data:/data
  tor-socks-proxy-local:
    container_name: tor-socks-proxy
    image: peterdavehello/tor-socks-proxy:latest
    ports:
      - "127.0.0.1:8853:53/udp"
      - "127.0.0.1:9150:9150/tcp"
    expose:
      - 9150
    restart: unless-stopped

volumes:
  redis-data:
