version: "3.7"
services:
  checker:
    build:
      context: .
      dockerfile: Dockerfile_checker
    volumes:
      - ./output:/code/output
    environment:
      TZ: Europe/Prague
  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    volumes:
      - ./output:/code/output
    environment:
      TELEGRAM_BOT_TOKEN: "$TELEGRAM_BOT_TOKEN"
      DEVELOPER_CHAT_ID: "$DEVELOPER_CHAT_ID"
      POLLING_INTERVAL: 17
      TZ: Europe/Prague
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
       - ./storage/redis/data:/data
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 9000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./output:/code/output:ro
    environment:
      GF_INSTALL_PLUGINS: "marcusolsson-csv-datasource"
      GF_SECURITY_ADMIN_USER: "$GRAFANA_ADMIN_USER"
      GF_SECURITY_ADMIN_PASSWORD: "$GRAFANA_ADMIN_PASSWORD"
      GF_PLUGIN_MARCUSOLSSON_CSV_DATASOURCE_ALLOW_LOCAL_MODE: "true"
      GF_PLUGIN_ALLOW_LOCAL_MODE: "true"

volumes:
  redis-data:
  grafana-data:
