version: "3.7"
services:
  checker:
    build:
      context: .
      dockerfile: Dockerfile_checker
    volumes:
      - ./output:/code/output
    environment:
      TZ: Europe/Prague
  bot:
    build:
      context: .
      dockerfile: Dockerfile_bot
    volumes:
      - ./output:/code/output
    environment:
      TELEGRAM_BOT_TOKEN: "$TELEGRAM_BOT_TOKEN"
      TZ: Europe/Prague
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes
    volumes:
       - ./storage/redis/data:/data

volumes:
  redis-data:
