[build-system]
requires = [
    "asyncio",
    "beautifulsoup4",
    "lxml",
    "pytest",
    "pytz",
    "requests",
    "unidecode",

    "python-telegram-bot==13.5",
    "redis",
    "unidecode",
    "setuptools"
]
build-backend = "setuptools.build_meta"
